name: Bot CI\CD

on:
  push:
    branches: [ main ]

jobs:    
  build:
    name: Build and push BOT Docker Image
    runs-on: ubuntu-latest

    steps:
      - name: Build Debug Info
        run: |
          echo "DOCKERHUB_USERNAME: ${{ vars.DOCKERHUB_USERNAME }}"
          echo "DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}"
          echo "DOCKERHUB_REPO: ${{ vars.DOCKERHUB_REPO }}"
          echo "DOCKERHUB_TAG: ${{ vars.DOCKERHUB_TAG }}"
        
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Github Packages
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build image and push to Docker Hub
        uses: docker/build-push-action@v3
        with:
          context: .
          tags: |
            ${{ vars.DOCKERHUB_USERNAME }}/${{ vars.DOCKERHUB_REPO }}:${{ vars.DOCKERHUB_TAG }}
          push: true

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
        
  deploy:
    name: Deploy BOT on Server
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Deploy Debug Info
        run: |
          echo "Starting Deploy..."
